### PR TITLE
Get rid of ppl_shim issue #13

### PR DESCRIPTION
**Pull request by vinklein**
Work related to issue #13 .

NB : increment operator of iterators are still writen in old style declaration due to some issue

### CODE REVIEW

**Comment by videlec** [comment]
Why these two changes

    -        assert self.thisptr!=NULL, 'Do not construct Poly_Con_Relation objects manually!'
    +        assert(self.thisptr!=NULL, 'Do not construct Poly_Con_Relation objects manually!')

and

    -        assert self.thisptr!=NULL, 'Do not construct Poly_Gen_Relation objects manually!'
    +        assert(self.thisptr!=NULL, 'Do not construct Poly_Gen_Relation objects manually!')

You can check that is very wrong within a Python shell

    >>> assert False, 'hello'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AssertionError: hello
    >>> assert (False, 'hello')
    <stdin>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?

**Comment by videlec** [comment]
Cython supports yield statements. You should try to get rid of the class `MIP_Problem_constraints_iterator` completely. That is to say, write directly the iterator inside the `__iter__` method.

**Comment by vinklein** [comment]
Interesting, i am on it.

**Comment by videlec** [comment]
Are you sure you need all these casts?

    if (<PPL_gs_iterator>self.gsi_ptr[0]) == (<Generator_System>self.gs).thisptr[0].end()

the following fails?

        if self.gsi_ptr[0] == self.gs.thisptr[0].end()

**Comment by vinklein** [comment]
No you're right the later work too.

**Comment by videlec** [comment]
I don't think so many casts are necessary

    yield _wrap_Generator(deref((<PPL_gs_iterator&>gsi_ptr[0]).inc(1)))

might be replaced by

    yield _wrap_Generator(deref((gsi_ptr[0]).inc(1)))

No?

**Comment by vinklein** [comment]
I was pretty sure it's a necessity but you're right again. And we can 
gain two more char this way

|yield _wrap_Generator(deref(gsi_ptr[0].inc(1))) |

gsi_ptr used to be of gsi_iterator_ptr type that explain the outdated cast.

**Comment by videlec** [comment]
No need to put

    Wrap PPL's ``Generator_System::const_iterator`` class.

in the docstring of  `__iter__`.  The latter is just a fuction. It does not really wrap anything.

**Comment by videlec** [comment]
In Cython, you would better not put paranthesis for while, in other words prefer

    while mip_it[0] != self.thisptr[0].constraints_end()
        # do someting

better than

    while(mip_it[0] != self.thisptr[0].constraints_end()):
        # do someting

**Comment by videlec** [comment]
It is a good convention to have a new line at the end of the file (should be configurable in the editor).

**Comment by videlec** [comment]
Thanks!

If you think about a way of testing that the memory is correctly deallocated (possibly using valgrind) it would be nice to include it somewhere.

**Pull request merged**
