### PR TITLE
adding widening

### PR DESCRIPTION
**Pull request by jesusjda**
#25 
Please check comments

### CODE REVIEW

**Comment by videlec** [comment]
You need to add tests to the documentation. It consists of a sequence of inputs and outputs. These tests will be automatically run on Travis-CI. Here is an example from the method `space_dimension`
```
Examples:

>>> from ppl import Variable, C_Polyhedron
>>> x = Variable(0)
>>> y = Variable(1)
>>> p = C_Polyhedron( 5*x-2*y >=  x+y-1 )
>>> p.space_dimension()
2
```
It is also a good practice to include test case raising errors such as the following from `relation_with`
```
>>> z = Variable(2)
>>> p.relation_with( point(x+y+z) )
Traceback (most recent call last):
...
ValueError: PPL::C_Polyhedron::relation_with(g):
this->space_dimension() == 2, g.space_dimension() == 3.
```
(the ellipsis `...` matches anything)

**Comment by jesusjda** [comment]
All the examples, but one, are from the ppl library. I added one who raises an ValueError Exception

**Comment by videlec** [comment]
Looks better. In your OUTPUT section you do not describe the output! Could you add some words saying that you return the new value of tp?

**Comment by jesusjda** [comment]
Done, Thanks

**Comment by videlec** [comment]
Last thing. The examples serve two purposes: test and documentation. Could you add some examples on the usage of tp and the output value?

**Comment by videlec** [comment]
Thanks!

**Pull request merged**
